# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c
sudo: required
dist: trusty
script: ./travis-tool.sh run_tests

before_script:
  - sudo apt-get update
  - sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev netcdf-bin libproj-dev libv8-dev
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_deps
  
install_github:
 - jimhester/covr
 
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

env:
   global:
     - R_LIBS="http://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""
     - NOT_CRAN="true"

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
