language: r

r:
  - oldrel
  - release
  - devel

cache: packages
sudo: required
dist: trusty

addons:
  postgresql: "9.6"

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - sudo apt-get --yes install libjson-c-dev postgresql-server-dev-9.6
  - wget http://download.osgeo.org/postgis/source/postgis-2.3.2.tar.gz
  - (mv postgis* /tmp; cd /tmp; tar xzf postgis-2.3.2.tar.gz)
  - (cd /tmp/postgis-2.3.2 ; ./configure; make; sudo make install)

warnings_are_errors: true

after_success:
  - Rscript -e "library(covr); codecov()"

before_script:
  - sudo apt-get update
  - sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev netcdf-bin libproj-dev libv8-dev
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_deps
