# ref) https://github.com/edzer/sf_dep/blob/master/.travis.yml

dist: trusty
language: R
sudo: required
cache: packages

r:
- oldrel
- release
# - devel

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

warnings_are_errors: true

after_success:
  - Rscript -e 'covr::codecov()'
